const $=s=>document.querySelector(s), money=n=>'€'+Number(n||0).toFixed(2); let data;
function role(){return $('#role').value} function show(id){document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$('#'+id).classList.remove('hidden')}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.tab));
async function api(url,opts){const r=await fetch(url,opts);const j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j}
function render(){if(!data)return;const f=data.financials;$('#totals').innerHTML=[['Project A',f.A],['Project B',f.B],['Whole company',f.company]].map(([n,x])=>`<div class="card"><small>${n}</small><strong>${money(x.result)}</strong><small>Approved income ${money(x.income)}<br>Commissions ${money(x.commissions)}<br>Expenses ${money(x.expenses)}</small></div>`).join('');$('#earned').innerHTML=Object.entries(f.earned).map(([n,v])=>`<div class="card"><small>${n}</small><strong>${money(v)}</strong></div>`).join('');$('#reconcile').textContent=`A + B − ${money(f.overhead)} overhead − ${money(f.awaiting)} awaiting allocation = ${money(f.company.result)}`;
 const records=data.records||[];$('#recordList').innerHTML=records.length?records.map(x=>`<article class="record"><b>${x.reference}</b> · ${x.type} · ${money(x.amount)} · ${x.status}<br>${x.description}<br><small>Original: ${x.type==='sale'?JSON.stringify(x.proposed_split):x.proposed_allocation} · Final: ${x.type==='sale'?(x.final_split?JSON.stringify(x.final_split):'—'):(x.final_allocation||'—')}</small></article>`).join(''):'<p>No records for this role.</p>';
 const pending=(data.manager?.all||[]).filter(x=>x.status==='Pending');
 const decisions=pending.map(x=>{
   if(x.type==='sale') return `<form class="decision" data-ref="${x.reference}" data-type="sale"><b>${x.reference}</b> ${money(x.amount)} · original ${JSON.stringify(x.proposed_split)}<br><input name="richard" value="${x.proposed_split.richard}"> Richard <input name="anastasia" value="${x.proposed_split.anastasia}"> Anastasia <input name="jean-claude" value="${x.proposed_split['jean-claude']}"> Jean-Claude <button>Approve sale</button></form>`;
   return `<form class="decision" data-ref="${x.reference}" data-type="expense"><b>${x.reference}</b> ${money(x.amount)} · proposed ${x.proposed_allocation}<br><select name="allocation"><option>A</option><option>B</option><option>Overhead</option></select><button>Approve expense</button></form>`;
 }).join('');
 $('#decisions').innerHTML=data.role==='manager'?'<h2>Pending manager decisions</h2>'+(decisions||'<p>Nothing awaiting approval.</p>'):'';
 document.querySelectorAll('.decision').forEach(form=>form.onsubmit=approve);$('#saleForm').style.display=data.role==='sales'?'block':'none';$('#expenseForm').style.display=data.role==='expenses'?'block':'none';$('#submitHint').textContent=data.role==='manager'?'Svetlana approves but does not make routine entries.':data.role==='sales'?'Only your sales are returned from the server.':'Only your expenses are returned from the server.';$('#linkForm').style.display=data.role==='manager'?'block':'none';}
async function load(){try{data=await api('/api/dashboard?actor='+encodeURIComponent(role()));render()}catch(e){$('#notice').textContent=e.message}}
$('#role').onchange=load;
$('#saleForm').onsubmit=async e=>{e.preventDefault();let x=Object.fromEntries(new FormData(e.target));try{await api('/api/transactions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor:role(),type:'sale',...x,split:{richard:+x.richard,anastasia:+x.anastasia,'jean-claude':+x.jean}})});e.target.reset();await load();alert('Saved as Pending. It does not affect income until Svetlana approves it.')}catch(err){alert(err.message)}};
$('#expenseForm').onsubmit=async e=>{e.preventDefault();let x=Object.fromEntries(new FormData(e.target));try{await api('/api/transactions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor:role(),type:'expense',...x})});e.target.reset();await load();alert('Paid expense saved. It affects company result immediately.')}catch(err){alert(err.message)}};
async function approve(e){e.preventDefault();const x=Object.fromEntries(new FormData(e.target));try{await api('/api/decision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor:role(),reference:e.target.dataset.ref,split:e.target.dataset.type==='sale'?{richard:+x.richard,anastasia:+x.anastasia,'jean-claude':+x['jean-claude']}:undefined,allocation:x.allocation})});await load()}catch(err){alert(err.message)}}
$('#linkForm').onsubmit=async e=>{e.preventDefault();try{const x=Object.fromEntries(new FormData(e.target));await api('/api/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor:role(),...x})});alert('Telegram link saved. Past submissions keep their original reply chat.')}catch(err){alert(err.message)}}; load();
